// EF Core Migrations History

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

BEGIN;

CREATE TABLE IF NOT EXISTS "admin_users" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" text NOT NULL,
    "password_hash" text NOT NULL,
    "role" text NOT NULL,
    "created_at" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "device_logs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SerialNo" text NOT NULL,
    "Action" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "devices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SerialNo" text NOT NULL,
    "DeviceName" text NOT NULL,
    "AuthMode" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "DelFlg" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL
);

INSERT INTO "admin_users" ("id", "created_at", "password_hash", "role", "username")
VALUES (1, TIMESTAMPTZ '2025-12-05 00:00:00+00', '39f8485ae66793496c7f4e437acfa60d3905653ea01ca155cf1b5d05446f3702', 'super_admin', 'admin')
ON CONFLICT ("id") DO NOTHING;

SELECT setval(pg_get_serial_sequence('"admin_users"', 'id'), (SELECT MAX("id") FROM "admin_users"));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251208033307_InitClean', '8.0.10')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
